apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "nexusops.fullname" . }}-uploads
  labels:
    {{- include "nexusops.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.uploads.pvcSize | default "5Gi" }}
