export default {
  index: "Overview",
  tickets: "Tickets",
  workflows: "Workflows",
  "service-desk-sep": {
    type: "separator",
    title: "People & Workplace",
  },
  hr: "HR & Employee Services",
  payroll: "Payroll",
  recruitment: "Recruitment",
  performance: "Performance",
  "finance-sep": {
    type: "separator",
    title: "Finance & Procurement",
  },
  accounting: "Accounting",
  "india-tax": "GST & TDS",
  procurement: "Procurement",
  vendors: "Vendors & Contracts",
  "gov-sep": {
    type: "separator",
    title: "Governance & Other",
  },
  secretarial: "Legal & Governance",
  "security-grc": "Security & Compliance",
  approvals: "Approvals & Workflow",
  "customer-sales": "Customer & Sales",
  strategy: "Strategy & Projects",
};
